os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 1jul_500k29_01
      script: 
        - echo "condition with jhjhob testestt"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
